---
- name: clean yum 
  command: yum clean all
  
- name: Install Tools
  yum:
   state: present
   name:
    - telnet
    - htop
    
    
- name: Install php-fpm and deps
  yum: 
   state: present
   name:
      - php
      - php-cli
      - php-common
      - php-fpm
      - php-json
      - php-mbstring
      - php-mysqlnd
      - php-pdo
      - php-process
      - php-xml
  notify: restart php-fpm
