---
- name: add Repo php7
  command: rpm -Uvh  http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm
  command: rpm -Uvh  https://mirror.webtatic.com/yum/el7/webtatic-release.rpm
 
- name: Install Tools
  yum:
   state: present
   name:
    - telnet
    - htop
    
    
- name: Install php-fpm and deps
  yum: 
   state: present
   name:
      - php70.x86_64
      - php70-cli.x86_64
      - php70-common.x86_64
      - php70-fpm.x86_64
      - php70-json.x86_64
      - php70-mbstring.x86_64
      - php70-mysqlnd.x86_64
      - php70-pdo.x86_64
      - php70-process.x86_64
      - php70-xml.x86_64
  notify: restart php-fpm
