---
#- name: install pcre and openssl
#  yum: name={{item}} state=present
#  with_items:
#    - pcre-devel
#    - pcre-tools
#    - openssl
#    - openssl-devel

- name: add yum-utils
  yum: name=yum-utils state=present

- name: get openresty repo
  command: yum-config-manager --add-repo https://openresty.org/package/amazon/openresty.repo

- name: turn off interactive repo check
  command: sed -i 's/^repo_gpgcheck/#repo_gpgcheck/' /etc/yum.repos.d/openresty.repo

- name: install openresty
  yum: name=openresty state=present

- name: create nginx group
  group: name=nginx state=present

- name: create nginx user
  user: name=nginx group=nginx

- name: copy nginx conf file
  copy: src=nginx.conf dest=/usr/local/openresty/nginx/conf

- name: copy logrotate config file
  copy: src=nginx dest=/etc/logrotate.d/nginx owner=nginx group=nginx

- name: copy service script for nginx
  copy: src=nginx-init dest=/etc/init.d/nginx mode=a+x

- name: allocate directories for nginx
  file: path={{item}} owner=nginx group=nginx state=directory
  with_items:
    - /var/lib/nginx
    - /var/lib/nginx/body
    - /var/lib/nginx/fastcgi
  notify: start nginx service
